language: go

sudo: false

matrix:
  include:
    - go: 1.4
    - go: 1.3

install:
  - go get github.com/tools/godep
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls

script:
  - bin/test -v -race
  - $HOME/gopath/bin/goveralls -service=travis-ci
