sudo: false

language: go

matrix:
    include:
        - go: 1.4
        - go: 1.3

install:
    - go get github.com/tools/godep
    - go get github.com/mattn/goveralls

script:
    - godep go test -v ${TRAVIS_BUILD_DIR}/...
    - godep go test -v ${TRAVIS_BUILD_DIR}/... -race

