sudo: false

language: go

matrix:
    include:
        - go: 1.4
        - go: 1.3

install:
    - go get github.com/mattn/goveralls
    - GOPATH=$PWD/Godeps/_workspace:$GOPATH go install ./...

script:
    - go test -v ./...
    - go test -race -v ./...

